### PR TITLE
Port to Gnome Shell 45

### PR DESCRIPTION
**Pull request by Leleat**
(Updated)

~~Almost~~ everything should work now. ~~Known issue(s)~~:

- [x] When using the setting `tilegroups-in-app-switcher`, which isn't exposed via GUI (anymore), the normal app switcher becomes really small

scr

### CODE REVIEW

**Comment by 3v1n0** [comment]
Cool, thanks for starting this, wondering if you would be happy to do some I did in https://github.com/micheleg/dash-to-dock/pull/2070 so that we have a `dependencies` js files to handle things in a cleaner way, instead of repeating the same multiple times.

I'll try to work on this too, if you don't mind so let me know if you're fine with me pushing with this branch or I should do another one to merge with yours.

**Comment by Leleat** [comment]
> Cool, thanks for starting this, wondering if you would be happy to do some I did in https://github.com/micheleg/dash-to-dock/pull/2070 so that we have a dependencies js files to handle things in a cleaner way, instead of repeating the same multiple times.

Sure, works for me.

> I'll try to work on this too, if you don't mind so let me know if you're fine with me pushing with this branch or I should do another one to merge with yours.

Thanks 👍 feel free to directly push against this branch, if you want to.

**Comment by Leleat** [comment]
I've fixed the prefs. I'll look into `dependencies` during the weekend and do some testing and cleaning up `altTab.js`, if you haven't done more until then.

**Comment by Leleat** [comment]
Okay, almost everything seems to be working now. Only 1 broken thing left to fix:

- [ ] When using the setting `tilegroups-in-app-switcher`, which isn't exposed via GUI (anymore), the normal app switcher becomes really small

scr

AFAICT, I've only ported `altTab.js` to ESM... so not sure what changed yet

**Comment by Leleat** [comment]
Alright, everything seems to be working now (from a testing in a vm).

**Pull request merged**
