### PR TITLE
Gnome 42 compatibility fixes/hacks

### LINKED ISSUE #144: Port to GNOME 42
**Describe the bug**

Does not show tile window placeholder, nor does it tile any window.

**Steps To Reproduce**

1. Install GNOME 42~alpha for your distribution
2. Download 
3. Add version 42 to meta data
4. enable extension
5. Try to drag any to the side
6. See that it does not tile

**System Info:**
 - Distro (incl. version): Ubuntu Jammy Jellyfish (development version)
 - GNOME (Shell) version: 42.alpha
 - Extension version and from where (e. g. EGO, `main` branch...): master
 - XOrg/Wayland: XOrg

**Journalctl logs**

```
Window manager warning: Overwriting existing binding of keysym 39 with keysym 39 (keycode 12).
Window manager warning: Overwriting existing binding of keysym 31 with keysym 31 (keycode a).
Window manager warning: Overwriting existing binding of keysym 32 with keysym 32 (keycode b).
Window manager warning: Overwriting existing binding of keysym 34 with keysym 34 (keycode d).
Window manager warning: Overwriting existing binding of keysym 35 with keysym 35 (keycode e).
Window manager warning: Overwriting existing binding of keysym 38 with keysym 38 (keycode 11).
Window manager warning: Overwriting existing binding of keysym 33 with keysym 33 (keycode c).
Window manager warning: Overwriting existing binding of keysym 36 with keysym 36 (keycode f).
Window manager warning: Overwriting existing binding of keysym 39 with keysym 39 (keycode 12).
Window manager warning: Overwriting existing binding of keysym 37 with keysym 37 (keycode 10).
```

### PR DESCRIPTION
**Pull request by Alabate**
I made some fixes and hacks to make this extension work on Gnome-shell 42.0 (Ubuntu 22.04). Fixes #144.

I don't really expect this PR to be merged because some of those fixes are just feature removal. This PR also break compatibility with old gnome-shell versions, I don't know if it's an issue. However it seems to work on my system and can maybe help maintainers to make a propre upgrade to this extension.

### Fixes

- `fadeAndDestroy()` expect a `this._grab` attribute
    - `pushModal()` now return a `grab` object instead of a boolean ([diff](https://github.com/GNOME/gnome-shell/commit/7419674bd39b0ac644b3fdb1cb5ba584f20526ee#diff-fbad094aec08ac6767eceb5dcfe9986d687c61f6d83b49b77544b0e02781d5fcL542))
    - This grab object is expected to be fed to `popModal()` ([diff](https://github.com/GNOME/gnome-shell/commit/7419674bd39b0ac644b3fdb1cb5ba584f20526ee#diff-fbad094aec08ac6767eceb5dcfe9986d687c61f6d83b49b77544b0e02781d5fcL597))
    - `super.fadeAndDestro()` use the `this._grab` attribute to call `popModal()`, so we need to define it ([source](https://github.com/GNOME/gnome-shell/blob/42.0/js/ui/switcherPopup.js#L311))
    - I fixed it by copying the update of `SwitcherPopup.show()` and applying it to  `TilingSwitcherPopup.show()`. ([source](https://github.com/GNOME/gnome-shell/blob/42.0/js/ui/switcherPopup.js#L105))
- `AppSwitcher._addIcon()` now use `appIcon.app.connectObject` instead of `appIcon.app.connect`
    - Source: https://github.com/GNOME/gnome-shell/blob/42.0/js/ui/altTab.js#L868
    - I just defined `connectObject` like `connect` was defined

### Hacks/Feature removal

- `set_titlebar()` not supported by libadwaita 
    - Source: https://gitlab.gnome.org/GNOME/libadwaita/-/blob/main/src/adw-window.c#L41
    - I just removed the call, I don't really know what that function was doing.

- All `_onMoving()` event were always ignored
   - It seems that in my case all `Clutter.get_current_event()` was always null.
   - I just removed it, maybe it will break the extension on touchscreens?

### CODE REVIEW

**Comment by piotrzientarski** [comment]
The first thing I noticed is that Tile Editing Mode is not working.
```
JS ERROR: Error: incorrect pop
popModal@resource:///org/gnome/shell/ui/main.js:623:15
close@/home/piotrek/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/tileEditingMode.js:96:18
vfunc_button_press_event@/home/piotrek/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/tileEditingMode.js:120:14
```

**Comment by Leleat** [comment]
> This PR also break compatibility with old gnome-shell versions, I don't know if it's an issue.

No issue for me. I personally only 'support' the latest GNOME version.

>  All _onMoving() event were always ignored
> It seems that in my case all Clutter.get_current_event() was always null.
> I just removed it, maybe it will break the extension on touchscreens?

Same for me on Fedora Beta. So I also just removed that entirely on my local branch since I don't have a touchscreen and have no clue how they actually work. It was added by trial and error with the help of some user in the past... But touch never fully worked anyway (see the other issue about touch).

> set_titlebar() not supported by libadwaita
> I just removed the call, I don't really know what that function was doing.

It just added the tabs into the title bar. Here is an image https://github.com/Leleat/Tiling-Assistant/blob/main/GUIDE.md. The prefs window needs to be ported to Libadwaita. It's what I am currently working on. Although it's only in the early stages (i. e. I am familiarizing myself with libadwaita atm).

If you want to continue working on this and have it merged, feel free to tell me and I push my local stuff (which isn't that much IIRC).

**Comment by dolwup** [comment]
I tried this MR on my laptop and adaptive tiling (holding ctrl while dragging a window) doesn't seem to work.
I don't know if thats related to the _onMoving() event stuff you mentioned, since I don't really know anything about making extension. I'm happy to help testing though

**Comment by Leleat** [comment]
I've fully ported the extension to GNOME 42 in `main` now. So this is not needed anymore. Brave testers would be appreciated :) Please report issues in https://github.com/Leleat/Tiling-Assistant/issues/144. After some further testing I'll upload it to EGO.

**Pull request closed without merging**
