### PR TITLE
Implemented individual screen gaps

### PR DESCRIPTION
**Pull request by CharlieQLe**
Figured that I'd open a PR for this. It seems to work fine for me, but I don't usually have tiling setups more complex than quarter tiling. This should close issue #146.

### CODE REVIEW

**Comment by Leleat** [comment]
Thanks for the PR.

I noticed 2 issues

gaps

1. It looks like you didn't adjust the window's size if it has gaps around it. You can see that the windows extend beyond/touch the bottom screen edge.
2. The screen edge gaps are also applied between windows.

If it helps with debugging: in the 'hidden settings' (accessed via the popup menu in the prefs) there are 2 keyboard shortcuts to visualize the (actual) tiles of the windows. The shortcuts act as toggles. Here is an example

gaps2

**Comment by Leleat** [comment]
Found one last issue. The actual tiles (`tiledRect` properties) don't seem to be updated correctly in `_onResizeFinished()` in `tiling-assistant@leleat-on-github/src/extension/resizeHandler.js` if you resize on the S or E side when using asymmetric gaps for the top/bottom or left/right gaps respectively (on symmetric values it cancels each other?). You can visualize the actual tiles using the shortcut in the hidden settings.

Here are tiles after they were just tiled

pre

and here after a resize operation on the E side of the extension preferences

post

**Comment by CharlieQLe** [comment]
I believe that I updated the `tiledRect` properties correctly.

**Comment by Leleat** [comment]
Thanks!

**Pull request merged**
