### PR TITLE
Add support for Gnome 46

### PR DESCRIPTION
**Pull request by sergio-costas**
I tested it with Gnome 46 alpha using Fedora RawHide and it works fine just by updating the metadata file.

### CODE REVIEW

**Comment by jbicha** [comment]
The Tiling Assistant does not work with this merge request and GNOME Shell 46 Beta.

See https://gjs.guide/extensions/upgrading/gnome-shell-46.html for some hints

**Comment by Leleat** [comment]
Hmm, I am not aware of any (major) breaking changes on GNOME Shell/Mutter's side and the porting guide didn't list much that would affect Tiling Assistant.

I am gonna take a look at porting the extension to GNOME 46 this week or maybe the next week. It shouldn't be much work. I just want to make a new release for GNOME 45 with some bugfixes before that.

**Comment by jbicha** [comment]
I believe Sergio was planning to take a look. The keyboard shortcuts aren't working for me. Here's an error from my journal but the line numbers are slightly off because of an Ubuntu patch:

```
Unhandled promise rejection. To suppress this warning, add an error handler to
 your promise chain with .catch() or a try-catch block around your await expression.
 Stack trace of the failed promise:
tile@file:///usr/share/gnome-shell/extensions/tiling-assistant@ubuntu.com/src/extension/tilingWindowManager.js:123:22
toggleTiling@file:///usr/share/gnome-shell/extensions/tiling-assistant@ubuntu.com/src/extension/tilingWindowManager.js:982:18
_onCustomKeybindingPressed@file:///usr/share/gnome-shell/extensions/tiling-assistant@ubuntu.com/src/extension/keybindingHandler.js:207:25
@resource:///org/gnome/shell/ui/init.js:21:20
```

**Comment by sergio-costas** [comment]
Something happens in tilingWindowManager.js when calling `window.raise_and_make_recent()`... the code seems to hang.

**Comment by sergio-costas** [comment]
Removing that call, it works, but it still shows the "unhandled promise rejection" message.

**Comment by sergio-costas** [comment]
The message seems to be produced in the `await this.tryOpeningTilingPopup()` call, at line 227.

**Comment by sergio-costas** [comment]
Ok, this last commit fixes the problem, but doesn't send the window to the top. I'll check how to replace the `raise_and_make_recent()` call.

**Comment by sergio-costas** [comment]
Found the fix for `raise_and_make_recent()`; now it is `raise_and_make_recent_on_workspace()`.

@jbicha This patch should be complete.

**Comment by Leleat** [comment]
Haven't tested this yet, so just my initial thoughts when looking at the code:

I don't mind dropping support for GNOME 45 from `main`. Now that EGO also (kinda) supports branches I can just create a branch for a GNOME 45 bugfix release, if there are some major issues that need to be fixed there. So you can just replace `raise_and_make_recent` with `raise_and_make_recent_on_workspace`. But I leave it up to you since the compatibity code is fairly simple...

From what I can tell, there is no need for the `addActor` utility method. You can just replace `add_actor` with `add_child`.

**Comment by sergio-costas** [comment]
This extension is installed by default in Ubuntu, so to simplify maintenance, it's better to have full compatibility with Gnome 45.

About the `addActor()`, I had problems with `add_child()` in 45 when adapting dash-to-dock (it doesn't work! 🫨); that's why I prefer to use that.

**Comment by sergio-costas** [comment]
@jbicha I tested the keybindings and they work fine... Can you test them again, please?

**Comment by Leleat** [comment]
> About the addActor(), I had problems with add_child() in 45 when adapting dash-to-dock (it doesn't work! 🫨); that's why I prefer to use that.

Don't know what kind of problems you had but I never encountered issues with add_child (at least with `St.Widgets`) before. And having tried it locally, it works just fine on my end. So please remove the 'compatability' code for `addActor` since it isn't needed. After that I can merge this PR since everything seems to be working from my testing.

**Comment by sergio-costas** [comment]
Done.

**Comment by Leleat** [comment]
> Done.

Thanks, @sergio-costas. Do you want to wait for feedback from @jbicha about the keybindings issue? On my end, this is ready to be merged.

**Comment by sergio-costas** [comment]
@Leleat No problem. @jbicha ?

**Comment by jbicha** [comment]
Yes, the keyboard shortcuts are working for me now. Thank you!

**Comment by Leleat** [comment]
Thanks for the MR!

**Pull request merged**
