### PR TITLE
Update Brazillian Portuguese Translation

### PR DESCRIPTION
**Pull request by ItzJaum**
Added missing translations and improved existing ones based on context.

### CODE REVIEW

**Comment by nih0n** [comment]
Would be better if keep some terms in english. I've made a commit to your fork, if you agree with the adjustments could you please update the PR ?

**Comment by ItzJaum** [comment]
I wonder if there are some other terms we could leave in English too. It has been hard to find a *nice* translation to "tiling" and "tile", which are the main topics of the extension.

**Comment by Leleat** [comment]
Thanks for the work! Just leave a message here, if the PR is ready for a merge.

**Comment by Leleat** [comment]
> Done!
> This should be ready to merge

Thanks!

**Pull request merged**
