### PR TITLE
Fixes for the local build.

### PR DESCRIPTION
**Pull request by SubOptimal**
- removes a warning for the Japanese translation
- fixes the build; the locale directory in the extensions directory is removed before the generated locales are moved into it

### CODE REVIEW

**Comment by Leleat** [comment]
The second commit seems wrong to me and the build scripts works just fine here.

> fixes the build; the locale directory in the extensions directory is removed before the generated locales are moved into it

The `locale` directory is removed *after* the extension bundle is created (i. e. the `locale` dir is created and moved into the extension directory, then the bundle is zipped incl the `locale` dir, and finally `locale` is removed).

> mv: cannot move 'locale' to 'tiling-assistant@leleat-on-github/locale': Directory not empty

I don't include the `locale` directory in the repo and I remove generated `locale` directory in line 25 of the script... so I don't know how that directory already existed for you. Any way, I think we can just create the locale directory directly in L16 and 17. No idea why I completely overlooked that and started `mv`ing directories... So something like this

```bash
# compile tl: requires gettext
for FILE in translations/*.po; do
    LANG=$(basename "$FILE" .po)
    mkdir -p "tiling-assistant@leleat-on-github/locale/$LANG/LC_MESSAGES"
    msgfmt -c "$FILE" -o "tiling-assistant@leleat-on-github/locale/$LANG/LC_MESSAGES/tiling-assistant@leleat-on-github.mo"
done

# delete old package and create new zip package
rm -f tiling-assistant@leleat-on-github.shell-extension.zip
cd tiling-assistant@leleat-on-github
zip -qr tiling-assistant@leleat-on-github.shell-extension.zip ./*
mv tiling-assistant@leleat-on-github.shell-extension.zip ../
cd ..
```

**Comment by SubOptimal** [comment]
I found the reason it failed for me. One build failed and the directory `tiling-assistant@leleat-on-github/locale/` was still there for the next build.

So I would suggest keeping the removal of a leftover of `tiling-assistant@leleat-on-github/locale/` before moving the generated `locale/` directory. I reverted my previous commit partially, to keep the removal of the `locale/` directory after the build.

**Comment by SubOptimal** [comment]
I implemented your suggestion and removed the use of the temporary `locale/` directory.

**Comment by Leleat** [comment]
Thanks!

**Pull request merged**
